name: Check Videos

on:
  workflow_dispatch:  # Allows manual run
  schedule:
    - cron: "0 */3 * * *"  # Runs every 3 hours

jobs:
  update-videos:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Init proj
        run: npm init -y
      - name: install d
        run: npm install youtubei.js


      - name: Run script
        run: node scripts/check_videos.js

      - name: Commit and push if changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add downloads.json
          git diff --quiet && git diff --staged --quiet || git commit -m "Updated downloads.json with video titles"
          git push
