name: Sync Channel Data

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  sync-channel-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
        
      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Fetch and process data
        run: |
          node - <<'EOF'
          const https = require('https');

          function httpsGet(url) {
              return new Promise((resolve, reject) => {
                  https.get(url, (res) => {
                      let data = '';
                      res.on('data', (chunk) => data += chunk);
                      res.on('end', () => resolve(JSON.parse(data)));
                  }).on('error', reject);
              });
          }

          async function main() {
              try {
                  // Get existing downloads data
                  const downloads = await httpsGet(
                      'https://raw.githubusercontent.com/Studyleague01/srpay/main/downloads.json'
                  );

                  // Get channel data
                  const channelData = await httpsGet(
                      'https://cal1.piapi.ggtyler.dev/channel/UCPGNioeYrJq4nyAt-DVIHZg'
                  );

                  // Process videos
                  const result = {};
                  channelData.relatedStreams?.forEach(video => {
                      const id = video.url.split('=').pop();
                      if (downloads[id]) {
                          result[id] = {
                              title: video.title,
                              id: id,
                              filePath: downloads[id].filePath,
                              size: downloads[id].size
                          };
                      }
                  });

                  // Save result
                  require('fs').writeFileSync(
                      'channel.json',
                      JSON.stringify(result, null, 2)
                  );
              } catch (error) {
                  console.error('Error:', error);
                  process.exit(1);
              }
          }

          main();
          EOF

      - name: Commit changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add channel.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update channel data" && git push)
