name: Update Downloads

on:
  workflow_dispatch:  # Allows manual run
  schedule:
    - cron: "0 */3 * * *"  # Runs every 3 hours

jobs:
  update-downloads:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Init proj
        run: npm init -y
      - name: install d
        run: npm install youtubei.js

      - name: Run script to update downloads.json
        run: node scripts/check_videos.js

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add downloads.json
          git commit -m "Updated downloads.json via GitHub Actions" || echo "No changes to commit"
          git push
